lex-reporter/force-app/main/default/objects/Table_View__c/Table_View__c.object-meta.xml
<CustomObject>
    <description>Keeps table state from the end user&apos;s last Lightning Reporter view so that the application can provide analysis on what has changed between the last view and the same table&apos;s current state</description>
    <label>Table View</label>
    <nameField>
        <label>Table View Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Table Views</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

lex-reporter/force-app/main/default/objects/Table_View__c/fields/Context_Id__c.field-meta.xml
<CustomField>
    <fullName>Context_Id__c</fullName>
    <inlineHelpText>Id of record through which the Lightning Reporter was viewed</inlineHelpText>
    <label>Context Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

lex-reporter/force-app/main/default/objects/Table_View__c/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <inlineHelpText>The SObject name of the records in the view</inlineHelpText>
    <label>Object Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

lex-reporter/force-app/main/default/objects/Table_View__c/fields/Skinny_State__c.field-meta.xml
<CustomField>
    <fullName>Skinny_State__c</fullName>
    <label>Skinny State</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

lex-reporter/force-app/main/default/objects/Table_View__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <inlineHelpText>Includes all columns configured for this user for this view in the Lightning Reporter</inlineHelpText>
    <label>State</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

lex-reporter/force-app/main/default/objects/Table_View__c/fields/Viewer__c.field-meta.xml
<CustomField>
    <fullName>Viewer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Viewer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Table_Views</relationshipName>
    <type>Lookup</type>
</CustomField>

lex-reporter/force-app/main/default/classes/dto/TableViewDTO.cls
public class TableViewDTO {
  @AuraEnabled
  public String id { get; set; }
  @AuraEnabled
  public String objectName { get; set; }
  @AuraEnabled
  public String state { get; set; }
  @AuraEnabled
  public String skinnyState { get; set; }
  @AuraEnabled
  public String viewer { get; set; }
  @AuraEnabled
  public String contextId { get; set; }

  public TableViewDTO() {
  }

  public TableViewDTO(Table_View__c view) {
    this.id = view.Id;
    this.objectName = view.Object_Name__c;
    this.state = view.State__c;
    this.skinnyState = view.Skinny_State__c;
    this.viewer = view.Viewer__c;
    this.contextId = view.Context_Id__c;
  }

  public Table_View__c convertToDbModel() {
    return new Table_View__c(
      Id = this.id,
      Object_Name__c = this.objectName,
      State__c = this.state,
      Skinny_State__c = this.skinnyState,
      Viewer__c = this.viewer,
      Context_Id__c = this.contextId
    );
  }
}