lex-reporter/force-app/main/default/objects/Note_Metadata__c/Note_Metadata__c.object-meta.xml
<CustomObject>
    <description>Metadata about Note records created via the Lightning Reporter application</description>
    <label>Note Metadata</label>
    <nameField>
        <displayFormat>LRNM-{0000000}</displayFormat>
        <label>Note Metadata Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Note Metadata</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

lex-reporter/force-app/main/default/objects/Note_Metadata__c/fields/Viewed_By__c.field-meta.xml
<CustomField>
    <fullName>Viewed_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Tracks who viewed a Note in the Lightning Reporter component</inlineHelpText>
    <label>Viewed By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Note_Metadata</relationshipName>
    <type>Lookup</type>
</CustomField>

lex-reporter/force-app/main/default/classes/dto/NoteDTO.cls
public class NoteDTO{
    @AuraEnabled public Note note {get; set;}
    @AuraEnabled public Long localCreatedDate {get; set;}
    @AuraEnabled public String parentSObjectType {get; set;}
    @AuraEnabled public List<Note_Metadata__c> views = new List<Note_Metadata__c>();
    @AuraEnabled public Boolean alertRunningUser {get; set;}

    public NoteDTO(Note note, List<Note_Metadata__c> metadata){
        this.note = note;
        this.localCreatedDate = Datetime.parse(note.CreatedDate.format()).getTime(); // convert created date to local timezone
        this.parentSObjectType = note.ParentId.getSObjectType().getDescribe().getName();
        Set<Id> mentionedUserIds = new Set<Id>();
        Set<Id> viewedByUserIds = new Set<Id>();
        for(Note_Metadata__c md : metadata){
            if(md.Viewed_By__c != null){ // we only need views for FE
                views.add(md);
            }
        }
    }
}