lex-reporter/force-app/main/default/objects/Lightning_Reporter_Note_Metadata__c/Lightning_Reporter_Note_Metadata__c.object-meta.xml
<CustomObject>
    <description>Lightning Reporter-created Notes detail</description>
    <label>Lightning Reporter Note Metadata</label>
    <nameField>
        <displayFormat>LRNM-{0000000}</displayFormat>
        <label>Note Metadata Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lightning Reporter Note Metadata</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

lex-reporter/force-app/main/default/objects/Lightning_Reporter_Note_Metadata__c/fields/Mentioned_User__c.field-meta.xml
<CustomField>
    <fullName>Mentioned_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>A user who was mentioned in a Lex Reporter Note</inlineHelpText>
    <label>Mentioned User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Lightning_Reporter_Note_Metadata1</relationshipName>
    <type>Lookup</type>
</CustomField>

lex-reporter/force-app/main/default/objects/Lightning_Reporter_Note_Metadata__c/fields/Note_Id__c.field-meta.xml
<CustomField>
    <fullName>Note_Id__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Note Id to which this metadata record maps</inlineHelpText>
    <label>Note Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

lex-reporter/force-app/main/default/objects/Lightning_Reporter_Note_Metadata__c/fields/Viewed_By__c.field-meta.xml
<CustomField>
    <fullName>Viewed_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Tracks who viewed a Note in the Lightning Reporter component</inlineHelpText>
    <label>Viewed By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Lightning_Reporter_Note_Metadata</relationshipName>
    <type>Lookup</type>
</CustomField>

lex-reporter/force-app/main/default/classes/TableRowControllerTest.cls
@isTest
public class TableRowControllerTest {
    
    @TestSetup
    static void makeData(){
        // insert test account
        Account acc = new Account(Name = 'Test Account');
        insert acc;
        // insert test contact
        Contact con = new Contact(LastName = 'Test Contact', AccountId = acc.Id);
        insert con;
    }

    @isTest
    static void givenNoteWithMentions_verifyNoteAndRelatedMdSaved(){
        String runningUserName = UserInfo.getName();
        String noteBody = 'This is a test note with a mention of @<strong>'+runningUserName+'</strong>';

        Account acc = [SELECT Id FROM Account LIMIT 1];
        Contact con = [SELECT Id FROM Contact LIMIT 1];

        Test.startTest();
        DTO.NoteDTO n = TableRowController.saveNote(noteBody, con.Id, acc.Id);
        Test.stopTest();

        System.assertEquals(noteBody, n.note.Body);
        System.assertEquals(1, [SELECT count() 
                                  FROM Lightning_Reporter_Note_Metadata__c 
                                  WHERE Note_Id__c = :n.note.Id
                                        AND Mentioned_User__c = :UserInfo.getUserId()]);
    }

    @isTest
    static void givenNoteWithoutMentions_verifyNoteAndNoRelatedMdSaved(){
        String runningUserName = UserInfo.getName();
        String noteBody = 'This is just a test note';

        Account acc = [SELECT Id FROM Account LIMIT 1];
        Contact con = [SELECT Id FROM Contact LIMIT 1];

        Test.startTest();
        DTO.NoteDTO n = TableRowController.saveNote(noteBody, con.Id, acc.Id);
        Test.stopTest();

        System.assertEquals(noteBody, n.note.Body);
        System.assertEquals(0, [SELECT count() 
                                  FROM Lightning_Reporter_Note_Metadata__c 
                                  WHERE Note_Id__c = :n.note.Id
                                        AND Mentioned_User__c = :UserInfo.getUserId()]);
    }

    @isTest
    static void givenNote_verifyViewCounted(){
        String runningUserName = UserInfo.getName();
        String noteBody = 'This is just a test note';

        Account acc = [SELECT Id FROM Account LIMIT 1];
        Contact con = [SELECT Id FROM Contact LIMIT 1];

        DTO.NoteDTO n = TableRowController.saveNote(noteBody, con.Id, acc.Id);
        DTO.NoteMetadataDTO view = new DTO.NoteMetadataDTO();
        view.NoteId = n.note.Id;
        view.ViewedById = UserInfo.getUserId();
        view.NoteParentId = n.note.ParentId;
        view.TopMostId = acc.Id;

        Test.startTest();
        TableRowController.countView(view);
        Test.stopTest();

        System.assertEquals(1, [SELECT count()
                                FROM Lightning_Reporter_Note_Metadata__c
                                WHERE Viewed_By__c=: UserInfo.getUserId()]);
    }
}