lex-reporter/force-app/main/default/objects/Lightning_Reporter_Note_Metadata__c/Lightning_Reporter_Note_Metadata__c.object-meta.xml
<CustomObject>
    <description>Lightning Reporter-created Notes detail</description>
    <label>Lightning Reporter Note Metadata</label>
    <nameField>
        <displayFormat>LRNM-{0000000}</displayFormat>
        <label>Note Metadata Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lightning Reporter Note Metadata</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

lex-reporter/force-app/main/default/objects/Lightning_Reporter_Note_Metadata__c/fields/Note_Id__c.field-meta.xml
<CustomField>
    <fullName>Note_Id__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Note Id to which this metadata record maps</inlineHelpText>
    <label>Note Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

lex-reporter/force-app/main/default/objects/Lightning_Reporter_Note_Metadata__c/fields/Note_Parent_Id__c.field-meta.xml
<CustomField>
    <fullName>Note_Parent_Id__c</fullName>
    <inlineHelpText>The Parent Id of the related Note</inlineHelpText>
    <label>Note Parent Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

lex-reporter/force-app/main/default/objects/Lightning_Reporter_Note_Metadata__c/fields/Unique_Id__c.field-meta.xml
<CustomField>
    <fullName>Unique_Id__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Note Id + Viewed By Id</inlineHelpText>
    <label>Unique Id</label>
    <length>36</length>
    <type>Text</type>
</CustomField>

lex-reporter/force-app/main/default/objects/Lightning_Reporter_Note_Metadata__c/fields/Viewed_By__c.field-meta.xml
<CustomField>
    <fullName>Viewed_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Tracks who viewed a Note in the Lightning Reporter component</inlineHelpText>
    <label>Viewed By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Lightning_Reporter_Note_Metadata</relationshipName>
    <type>Lookup</type>
</CustomField>

lex-reporter/force-app/main/default/classes/TableRowController.cls
public with sharing class TableRowController {
    
    @AuraEnabled
    public static Note saveNote(String content, String parentId){
        Note newNote = new Note(Body=content,IsPrivate=false,ParentId=parentId,Title='LEX Reporter Note');
        insert newNote;
        return [SELECT CreatedDate,CreatedBy.Name,CreatedBy.FullPhotoUrl,Body 
                  FROM Note 
                  WHERE Id=:newNote.Id 
                  ORDER BY CreatedDate asc
                  LIMIT 1];
    }

    @AuraEnabled
    public static void saveNoteMetadata(NoteMetadataDTO noteMetadata){
        try {
            upsert noteMetadata.convertToDbModel() Lightning_Reporter_Note_Metadata__c.Unique_Id__c;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    public class NoteMetadataDTO{
        @AuraEnabled public String NoteId {get;set;}
        @AuraEnabled public String NoteParentId {get;set;}
        @AuraEnabled public String ViewedById {get;set;}

        public Lightning_Reporter_Note_Metadata__c convertToDbModel(){
            Lightning_Reporter_Note_Metadata__c noteMetadata = new Lightning_Reporter_Note_Metadata__c();
            noteMetadata.Note_Id__c = this.NoteId;
            noteMetadata.Note_Parent_Id__c = this.NoteParentId;
            noteMetadata.Viewed_By__c = (Id) this.ViewedById;
            noteMetadata.Unique_Id__c = this.NoteId + this.ViewedById;
            return noteMetadata;
        }
    }
}