lex-reporter/force-app/main/default/objects/LEX_Reporter_Table_Configuration__c/LEX_Reporter_Table_Configuration__c.object-meta.xml
<CustomObject>
    <label>LEX Reporter Table Configuration</label>
    <nameField>
        <label>LEX Reporter Table Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LEX Reporter Table Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

lex-reporter/force-app/main/default/objects/LEX_Reporter_Table_Configuration__c/fields/Default_Fieldset__c.field-meta.xml
<CustomField>
    <fullName>Default_Fieldset__c</fullName>
    <inlineHelpText>Comma separated list of fields (no spaces) to automatically include on LEX Reporter table initialization</inlineHelpText>
    <label>Default Fieldset</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

lex-reporter/force-app/main/default/classes/LightningReporterControllerTest2.cls
@isTest
public class LightningReporterControllerTest2 {
    
    @TestSetup
    static void makeData(){
        insert new LEX_Reporter_Table_Configuration__c(
            Default_Fieldset__c = 'Id,Name'
        );
    }

    @isTest
    static void givenDefaultTableConfiguration_verifyDefaultDTOs(){
        String defaultFields = [SELECT Default_Fieldset__C FROM LEX_Reporter_Table_Configuration__c LIMIT 1][0].Default_Fieldset__c;
        String objectType = 'Contact';

        // invoke LightningReporterController.getFieldsFromType()
        List<LightningReporterController.FieldDTO> dtos = LightningReporterController.getFieldsFromType(objectType);

        Integer numAssertions = 0;
        for(LightningReporterController.FieldDTO dto : dtos){            
            if(defaultFields.containsIgnoreCase(dto.name)){
                // System.assert(/** assert that default fieldset contains this default selected field */); 
                numAssertions++;
            }
        }

        // assert num assertions equals number of default fields (2)
    }
}